---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus
  namespace: repo-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          volumeMounts:
          - name: repo-nexus-data
            mountPath: /nexus-data
      containers:
        - name: nexus
          image: sonatype/nexus3:3.17.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081
            protocol: TCP
          volumeMounts:
          - name: repo-nexus-data
            mountPath: /nexus-data
      volumes:
        - name: repo-nexus-data
          persistentVolumeClaim:
            claimName: repo-nexus-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: nexus
  namespace: repo-nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 1111
  selector:
    app: nexus
